### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by N6RFM** [daniestevez/galileo-osnma#22]
Hi Dani,

Appreciate the update but I've hit a roadblock.  Any suggestions?  Thanks.  Bob N6RFM

bob@bob:~/galileo-osnma/osnma-longan-nano$ cargo clean
bob@bob:~/galileo-osnma/osnma-longan-nano$ cargo build --release
    Updating crates.io index
error: failed to select a version for the requirement `nb = "^1.0"`
candidate versions found which didn't match: 1.0.0, 0.1.3, 0.1.2, ...
location searched: crates.io index
required by package `osnma-longan-nano v0.1.0 (/home/bob/galileo-osnma/osnma-longan-nano)`
bob@bob:~/galileo-osnma/osnma-longan-nano$

**Comment by daniestevez** [comment]
Hi Bob,
I'm confused about your error, mainly because it's working for me (I tested on a new machine) and also works in CI, and because the error is complaining that it cannot find a version of `nb` matching `1.0`, but it says that it has found version `1.0.0` (which should match!).

Can you confirm that you're running this on a clean checkout (in particular that there are no local modifications in `Cargo.lock`) and also paste the output of `rustup show -v`?
